import Link from 'next/link';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import type { Note } from '@/lib/types';
import { Bot, Download, User } from 'lucide-react';

interface NoteCardProps {
  note: Note;
}

export function NoteCard({ note }: NoteCardProps) {
  return (
    <Link href={`/notes/${note.id}`} className="block transition-transform hover:scale-105">
      <Card className="h-full flex flex-col justify-between hover:border-primary/50 transition-colors duration-300">
        <CardHeader>
          <div className="absolute top-4 right-4 p-2 bg-accent/20 rounded-full">
            <Bot className="h-5 w-5 text-accent" />
          </div>
          <CardTitle className="pr-10">{note.title}</CardTitle>
          <CardDescription>{note.subject} - {note.semester}</CardDescription>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground line-clamp-3">{note.summary || 'Summary will be generated by AI.'}</p>
        </CardContent>
        <CardFooter className="flex-col items-start gap-4">
            <div className="flex flex-wrap gap-2">
                {note.keywords && note.keywords.slice(0, 3).map(keyword => (
                    <Badge key={keyword} variant="secondary">{keyword}</Badge>
                ))}
            </div>
          <div className="flex justify-between w-full text-xs text-muted-foreground">
            <div className="flex items-center gap-2">
                <User className="h-4 w-4" />
                <span>{note.teacherName}</span>
            </div>
            <div className="flex items-center gap-2">
                <Download className="h-4 w-4" />
                <span>{note.downloadCount}</span>
            </div>
          </div>
        </CardFooter>
      </Card>
    </Link>
  );
}
